before_commands:
    - "composer update --prefer-source"

tools:
    external_code_coverage: true
    php_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*", "tests/*"]
    sensiolabs_security_checker: true
            
checks:
    php:
        code_rating: true
        duplication: true