sudo: false

language: php

php:
    - '5.6'
  
before_install:
    - travis_retry composer self-update
  
install:
    - travis_retry composer install --no-interaction
    
script:
    - composer unit-tests
    
after_success:
    - travis_retry composer coveralls