sudo: false

language: php

php:
    - '5.6'
    
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
  
before_install:
    - travis_retry composer self-update
  
install:
    - travis_retry composer install --no-interaction
    
script:
    - composer unit-tests
    
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - composer scrutinizer-ocular
    
after_success:
    - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    - export CI_BRANCH="$TRAVIS_BRANCH"
    - travis_retry composer coveralls